environment:
  matrix:
  - nodejs_version: "8.0"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm i -g @angular/cli@1.7.4

test_script:
  - node --version
  - ng build

build: off
